"""应用层端口（仓储协议与事件发布协议，M2）。

- 应用层用例只依赖这些协议，不依赖 SQLAlchemy、psycopg 或具体存储，
  便于用内存实现做单元测试、用 PostgreSQL 实现跑生产（主基线 §30.3：
  API 层不直接写 ORM，Domain 层不依赖 FastAPI / SQLAlchemy）；
- 仓储实现按 ``CONTROL_PLANE_REPOSITORY`` 在组合根注入（``app/dependencies.py``）；
- 事件发布端口把"写操作 → 状态流"解耦，SSE 与轮询共用同一事件中心。
"""

from __future__ import annotations

from collections.abc import Sequence
from datetime import datetime
from typing import Any, Protocol

from app.domain.account import Account
from app.domain.audit import AuditEntry
from app.domain.catalog import FeatureGrant, ProductProfile
from app.domain.device import Device
from app.domain.license import License
from app.domain.session import Session
from app.domain.tenant import Tenant


class IdentityRepository(Protocol):
    """商户、账号与会话仓储。"""

    # ---- tenant ----
    def get_tenant(self, tenant_id: str) -> Tenant | None: ...
    def add_tenant(self, tenant: Tenant) -> None: ...

    # ---- account ----
    def get_account(self, account_id: str) -> Account | None: ...
    def get_account_by_login_name(self, login_name: str) -> Account | None: ...
    def add_account(self, account: Account) -> None: ...
    def save_account(self, account: Account) -> None: ...

    # ---- session ----
    def get_session(self, session_id: str) -> Session | None: ...
    def get_session_by_refresh_hash(self, token_hash: str) -> Session | None: ...
    def get_session_by_previous_refresh_hash(self, token_hash: str) -> Session | None:
        """按"刚被轮换掉"的指纹查找会话（Refresh Token 重放检测，见 domain/session.py）。"""
        ...
    def add_session(self, session: Session) -> None: ...
    def save_session(self, session: Session) -> None: ...
    def revoke_sessions_of_account(self, account_id: str, now: datetime) -> int:
        """撤销该账号全部有效会话，返回被撤销条数（重放检测与注销使用）。"""
        ...


class DeviceRepository(Protocol):
    """设备仓储。"""

    def get_device(self, device_id: str) -> Device | None: ...
    def get_device_by_fingerprint(self, tenant_id: str, fingerprint: str) -> Device | None: ...
    def list_devices(self, tenant_id: str) -> list[Device]: ...
    def add_device(self, device: Device) -> None: ...
    def save_device(self, device: Device) -> None: ...
    def count_registered_devices(self, tenant_id: str) -> int:
        """在册（未吊销）设备数，用于许可证 max_devices 校验。"""
        ...


class EntitlementRepository(Protocol):
    """行业类型、许可证与功能授权仓储。"""

    def get_product_profile(self, product_profile_id: str) -> ProductProfile | None: ...
    def add_product_profile(self, profile: ProductProfile) -> None: ...
    def get_license(self, license_id: str) -> License | None: ...
    def get_active_license(self, tenant_id: str) -> License | None: ...
    def add_license(self, license_: License) -> None: ...
    def save_license(self, license_: License) -> None: ...
    def list_feature_grants(self, tenant_id: str) -> list[FeatureGrant]: ...
    def add_feature_grant(self, grant: FeatureGrant) -> None: ...


class AuditRepository(Protocol):
    """审计仓储（只追加，不提供更新与删除入口）。"""

    def add(self, entry: AuditEntry) -> None: ...
    def list_for_tenant(self, tenant_id: str, limit: int = 100) -> Sequence[AuditEntry]: ...
    def list_for_actor(self, account_id: str, limit: int = 100) -> Sequence[AuditEntry]: ...


class EventPublisher(Protocol):
    """状态流事件发布端口（SSE 主通道与轮询降级共用同一事件中心）。"""

    def publish(self, tenant_id: str | None, event_type: str, payload: dict[str, Any]) -> str:
        """发布一条事件，返回事件 ID（供 SSE 的 ``id:`` 与 Last-Event-ID 续传）。"""
        ...
